# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-13 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neuron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80, verbose_name='neuron_name')),
                ('neuron_image', models.ImageField(blank=True, null=True, upload_to='Pic', verbose_name='neuron_picture')),
            ],
            options={
                'verbose_name': 'neuron_name',
                'verbose_name_plural': 'neuron_name',
            },
        ),
        migrations.CreateModel(
            name='NeuronClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='neuron_class_name')),
            ],
            options={
                'verbose_name': 'neuron_class_name',
                'verbose_name_plural': 'neuron_class_name',
            },
        ),
        migrations.AddField(
            model_name='neuron',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.NeuronClass'),
        ),
    ]
