# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-19 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuron',
            name='Class',
        ),
        migrations.AlterField(
            model_name='neuron',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.DeleteModel(
            name='NeuronClass',
        ),
    ]
