# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-19 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180419_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuron',
            name='near_neuron_list',
            field=models.CharField(default='', max_length=200, verbose_name='near_neuron_list'),
        ),
    ]
